### ISSUE TITLE
Youtube-dl not working

### ISSUE THREAD

**Issue by bellegarde-c** [flathub/org.gnome.Lollypop#189]
```
Traceback (most recent call last):
  File "/app/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.12.17', 'console_scripts', 'youtube-dl')())
  File "/app/bin/youtube-dl", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for youtube-dl
```

Any idea ? I'm trying to move Lollypop to yt-dlp but facing exactly the same issue.

**Comment by Eonfge** [comment]
I'm just following you here. I made an issue over on GNOME's Gitlab when Youtube-dl became deprecated and since then I'm waiting for your resolution.

https://gitlab.gnome.org/World/lollypop/-/issues/2840

My guess is that some of the Python headers have changed and therefore can't find it any more. yt-dlp is not API compatible with youtube-dl. Since they had to fork anyway, they instantly removed all deprecated logic.

https://github.com/yt-dlp/yt-dlp#differences-in-default-behavior

**Comment by bellegarde-c** [comment]
The issue is not with yt-dlp, it happens with current flathub package.

I'm just having the same issue with yt-dlp so I guess it's a python issue.

**Comment by Radical4ever** [comment]
maybe creating a flatpak runtime for yt-dlp would solve this issue?

**Comment by Eonfge** [comment]
I've updated the package with Lollypop 1.4.36 and yt-dlp, so I hope that everything is solved now.

**Comment by Radical4ever** [comment]
can confirm it works great now!
